export function AIGeneratedLabel() {
  return (
    <span className="text-[10px] uppercase tracking-[0.12em] text-[var(--color-soft)]" title="Generated by artificial intelligence">
      AI-generated
    </span>
  );
}
